org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx2048M
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true

kotlin.incremental=true
kotlin.code.style=official